theme: minima
title: Carlos Miyén Brandolino | Desarrollo de Software
description: Portafolio y perfil profesional de Carlos Miyén Brandolino. Explorando la intersección entre la gestión de negocios y la tecnología con un enfoque en Java, Desarrollo Web y Cloud.
author: Carlos Miyén Brandolino
